# Generated by Django 4.0.5 on 2022-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_end_day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='view_start_day',
            field=models.DateField(null=True),
        ),
    ]
