# Generated by Django 4.0.5 on 2022-06-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
